language: python
python:
        # Not supported, tests fail
        #- "2.6"
        - "2.7"
        # Not supported, tests fail
        #- "3.2"
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.5-dev" # 3.5 development branch
        - "nightly" # currently points to 3.6-dev
script: python -m unittest discover
notifications:
        email: false
